#!/usr/bin/env bash
#

# set -x # debug
set -e
set -u

d="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# if [ "$#" -lt 2 ]; then
#     echo "Usage: $0"
#     exit 1
# fi

"$d"/4git-branch --create "STASH_$(date +'%Y%m%d_%H%M%S')"
git add .
git commit -a -m '[WIP] 4git stash'


exit 0
