#!/usr/bin/env bash
set -e
set -u

d="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$d/4gitinit.sh"


git_rebase_cmd() {
    git rebase --interactive --autosquash "$@"
}

workspace_branch="$(4git-branch --base)"


get_upstream_branch() {
    leaf_branch="$("$d"/4git-branch-select || true)"
    if [ -z "$leaf_branch" ]; then
        echo "ERROR: no intermediary branch to rebase from out has been picked"
        exit 1
    fi
}

get_leaf_branch() {
    leaf_branch="$("$d"/4git-branch-select || true)"
    if [ -z "$leaf_branch" ]; then
        echo "ERROR: no leaf branch to rebase to has been picked"
        exit 1
    fi
}

case "$1" in; do
    --current)
        git_rebase_cmd "$worksprace_branch" $(current_branch)
        ;;
    --select)
        branch="$("$d"/4git-branch-select || true)"
        if [ -z "$branch" ]; then
            echo "ERROR: no branch picked"
            exit 1
        fi
        git_rebase_cmd "$worksprace_branch" $(branch)
        ;;
    --select-all)
        # this is first the cut off point, so the base branch
        branch="$("$d"/4git-branch-select || true)"
        if [ -z "$branch" ]; then
            echo "ERROR: no branch to rebase from picked"
            exit 1
        fi

        git_rebase_cmd --onto "$worksprace_branch" "$branch" "$leaf_branch"
        ;;
    --to-leaf)
        leaf_branch=$(get_leaf_branch)
        git_rebase_cmd --onto "$worksprace_branch" "$(current_branch)" "$leaf_branch"
        ;;
    --from-leaf)
        git_rebase_cmd --onto "$worksprace_branch" "" "$(current_branch)"
        ;;
esac


exit 0
