#!/usr/bin/env bash

set -e
set -u

d="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$d/4gitlib.sh"

base="$("$d"/4git-branch --base)"

branch="$("$d"/4git-branch-select || true)"
if [ -z "$branch" ]; then
    echo "ERROR: no branch picked"
    exit 1
fi

fzf_set_options --multi
commit=$(fzf-commit "$branch" "$base" | cut -d' ' -f1)
if [ -z "$commit" ]; then
    echo "ERROR: no commit picked"
    exit 2
fi

git cherry-pick "$commit"

exit 0




