#!/usr/bin/env bash

set -e
set -u


d="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$d/4gitlib.sh"

usage() {
    echo "Usage: $0 workspace-name"
    exit 1
}

# 1. use the current branch as the "upstream branch" as the base branch for our workspace

# because of 'set -e' this aborts here with a git error if were not in a git repository
REAL_BASE_BRANCH="$(git branch --show-current)"

# 2. read the workspace name
if [ "$#" -lt 1 ]; then
    WORKSPACE="$(4git_workspace)"
else
    WORKSPACE="${1:-$(4git_workspace)}"
fi

if [ -z "$WORKSPACE" ]; then
    echo "ERROR: Please provide a workspace name via an command line argument or use this from within tmux, where the window title is used."
    exit 2
fi

FOURGIT_BASE_BRANCH="4git/$REAL_BASE_BRANCH/$WORKSPACE"
# TODO: add this to env vars of tmux and/or direnv directly

# 3. create a branch
create_branch "$FOURGIT_BASE_BRANCH" "$REAL_BASE_BRANCH"

# 4. make sure the set the tmux window name correctly
set_4git_workspace "$WORKSPACE"


exit 0
